#!/bin/sh

set -eu

cd "$AUTOPKGTEST_TMP"

cat <<'EOF' > CMakeLists.txt
cmake_minimum_required(VERSION 3.13)

project("zycore-autopkgtest" LANGUAGES C)

find_package("zycore")

add_executable(main "${test_file}")
target_link_libraries(main Zycore::Zycore)
EOF

export CFLAGS='-Wall -Wextra -Wpedantic -Werror'

cmake -Dtest_file:FILEPATH="$OLDPWD/examples/String.c" -B build
cmake --build build
